name: Website
on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add common episodes
        run: |
          git clone https://github.com/enibigir/hsf-training-cicd-basics-webpage.git common
          cp common/_episodes/*.md _episodes/
          rm -rf common
          ls _episodes/

      - name: Ls

        run: ls

      - name: Build
        run: |
          docker run --rm \
          --volume="${{ github.workspace }}:/home/rstudio" \
          carpentries/lesson-docker:latest /bin/bash -c "gem install bundler && \
          bundle config --local set path .vendor/bundle && \
          bundle install && \
          bundle exec jekyll build --trace"

      - name: ls-after
        run: ls; ls _site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          enable_jekyll: false
